import { CMIP_REQUIRED_ASSET_SYMBOLS } from "../contracts/constants";

export const CMIP_GEMINI_SECTIONED_EXECUTION_VERSION = "CMIP-GEMINI-SECTIONED-EXECUTION-1.0";
export const CMIP_GEMINI_SECTIONED_ADAPTER_VERSION = "CMIP-GEMINI-SECTIONED-ADAPTER-1.0";
export const CMIP_GEMINI_SECTIONED_PLAN_VERSION = "CMIP-GEMINI-SECTION-PLAN-1.0";
export const CMIP_GEMINI_SECTION_SCHEMA_VERSION = "CMIP-GEMINI-SECTION-SCHEMA-1.0";
export const CMIP_GEMINI_SECTION_PROVIDER_PROJECTION_VERSION = "CMIP-GEMINI-SECTION-PROVIDER-PROJECTION-1.1";
export const CMIP_GEMINI_SECTION_CONTEXT_VERSION = "CMIP-GEMINI-SECTION-CONTEXT-1.0";
export const CMIP_GEMINI_SECTION_BUDGET_VERSION = "CMIP-GEMINI-SECTION-BUDGET-1.3";
export const CMIP_GEMINI_SECTION_THINKING_POLICY_VERSION = "CMIP-GEMINI-SECTION-THINKING-1.1";
export const CMIP_CANONICAL_SECTION_PARTITION_VERSION = "CMIP-CANONICAL-SECTION-PARTITION-1.0";
export const CMIP_CANONICAL_SECTION_DERIVATION_VERSION = "CMIP-CANONICAL-SECTION-DERIVATION-1.0";
export const CMIP_GEMINI_SECTION_SCHEMA_BYTE_BUDGET = 8192;
export const CMIP_GEMINI_SECTION_SCHEMA_MAX_DEPTH = 8;

export const CMIP_GEMINI_SECTION_IDS = [
  "meta_decision",
  "engines_reasons",
  "delta_attribution",
  "scenarios_triggers",
  "coins",
  "confidence_memory",
  "charts_audit",
] as const;

export const CMIP_GEMINI_SECTION_ORDER = [...CMIP_GEMINI_SECTION_IDS] as const;
export const CMIP_GEMINI_SECTION_COIN_SYMBOLS = CMIP_REQUIRED_ASSET_SYMBOLS;

export const CMIP_GEMINI_SECTION_ERROR_CODES = [
  "CMIP_EXPERIMENTAL_FULL_REPORT_AI_DISABLED",
  "CMIP_FULL_REPORT_TASK_TYPE_UNSUPPORTED",
  "GEMINI_SECTION_REQUEST_INVALID",
  "GEMINI_SECTION_SCHEMA_INVALID",
  "GEMINI_SECTION_SCHEMA_BUDGET_EXCEEDED",
  "GEMINI_SECTION_OUTPUT_MISSING",
  "GEMINI_SECTION_OUTPUT_JSON_INVALID",
  "GEMINI_SECTION_OUTPUT_INVALID",
  "GEMINI_SECTION_PROVIDER_FAILED",
  "GEMINI_SECTION_REFUSAL",
  "GEMINI_SECTION_INCOMPLETE",
  "GEMINI_SECTION_GENERATION_BUDGET_EXHAUSTED",
  "GEMINI_SECTION_REASONING_DOMINATED",
  "GEMINI_SECTION_ASSEMBLY_FAILED",
  "GEMINI_SECTION_FINAL_VALIDATION_FAILED",
  "GEMINI_SECTION_LIVE_SMOKE_NOT_ALLOWED",
  "GEMINI_SECTION_MODEL_PACKAGE_INVALID",
  "GEMINI_SECTION_MODEL_PACKAGE_INTEGRITY_INVALID",
  "GEMINI_SECTION_USAGE_INVALID",
  "GEMINI_SECTION_DUPLICATE_SECTION",
  "GEMINI_SECTION_MISSING_SECTION",
  "GEMINI_SECTION_UNEXPECTED_FIELD",
  "GEMINI_SECTION_NETWORK_FORBIDDEN",
  "GEMINI_SECTION_BUDGET_EXCEEDS_MODEL_LIMIT",
  "GEMINI_SECTION_CONTEXT_BUDGET_EXCEEDED",
  "GEMINI_SECTION_SOURCE_REF_UNRESOLVED",
] as const;

export const CMIP_GEMINI_SECTION_WARNING_CODES = [
  "GEMINI_SECTION_RETRY_ATTEMPTED",
  "GEMINI_SECTION_USAGE_UNAVAILABLE",
] as const;
