export const CMIP_GEMINI_EXECUTION_VERSION = "CMIP-GEMINI-EXECUTION-1.0";
export const CMIP_GEMINI_ADAPTER_VERSION = "CMIP-GEMINI-ADAPTER-1.0";
export const CMIP_GEMINI_SCHEMA_COMPATIBILITY_VERSION = "CMIP-GEMINI-SCHEMA-COMPAT-1.0";
export const CMIP_GEMINI_RESULT_SCHEMA_ID = "https://cmip.local/gemini/execution-result-schema.v1.json";
export const CMIP_GEMINI_MODEL_REGISTRY_VERSION = "CMIP-GEMINI-MODEL-REGISTRY-1.0";
export const CMIP_GEMINI_RETRY_POLICY_VERSION = "CMIP-GEMINI-RETRY-1.0";
export const CMIP_GEMINI_TOOL_POLICY_VERSION = "CMIP-GEMINI-TOOL-POLICY-1.0";

export const CMIP_GEMINI_MODEL_PROFILES = [
  "cmip_gemini_primary_reasoning",
  "cmip_gemini_fallback_reasoning",
  "cmip_gemini_validation_repair",
] as const;

export const CMIP_GEMINI_PROVIDER_STATUSES = ["completed", "incomplete", "failed", "cancelled", "in_progress", "queued", "blocked", "refused"] as const;

export const CMIP_GEMINI_ERROR_CODES = [
  "GEMINI_CONFIG_MISSING",
  "GEMINI_API_KEY_MISSING",
  "GEMINI_MODEL_NOT_CONFIGURED",
  "GEMINI_CLIENT_INIT_FAILED",
  "GEMINI_AUTHENTICATION_ERROR",
  "GEMINI_PERMISSION_ERROR",
  "GEMINI_RATE_LIMIT",
  "GEMINI_QUOTA_EXHAUSTED",
  "GEMINI_TIMEOUT",
  "GEMINI_TRANSPORT_ERROR",
  "GEMINI_PROVIDER_5XX",
  "GEMINI_INVALID_REQUEST",
  "GEMINI_MODEL_CAPABILITY_MISMATCH",
  "GEMINI_SCHEMA_INCOMPATIBLE",
  "GEMINI_RESPONSE_FAILED",
  "GEMINI_RESPONSE_INCOMPLETE",
  "GEMINI_RESPONSE_CANCELLED",
  "GEMINI_RESPONSE_UNEXPECTED_STATUS",
  "GEMINI_REFUSAL",
  "GEMINI_OUTPUT_MISSING",
  "GEMINI_OUTPUT_JSON_INVALID",
  "GEMINI_CANONICAL_OUTPUT_INVALID",
  "GEMINI_SCHEMA_REPAIR_FAILED",
  "GEMINI_RESULT_INVALID",
  "GEMINI_SEARCH_NOT_ALLOWED",
  "INVALID_GEMINI_EXECUTION_REQUEST",
  "MODEL_PACKAGE_INVALID",
  "MODEL_PACKAGE_INTEGRITY_INVALID",
  "OUTPUT_SCHEMA_MISMATCH",
  "OUTPUT_SCHEMA_UNSUPPORTED",
] as const;

export const CMIP_GEMINI_WARNING_CODES = [
  "GEMINI_RETRY_ATTEMPTED",
  "GEMINI_SCHEMA_REPAIR_ATTEMPTED",
  "GEMINI_GOOGLE_SEARCH_DISABLED_BY_ENV",
  "GEMINI_GOOGLE_SEARCH_UNSUPPORTED_BY_MODEL",
  "GEMINI_GOOGLE_SEARCH_DISABLED_BY_POLICY",
  "GEMINI_USAGE_UNAVAILABLE",
  "GEMINI_TOOL_SOURCE_RECORDED",
] as const;

export const CMIP_GEMINI_ENV_KEYS = [
  "GEMINI_API_KEY",
  "CMIP_GEMINI_MODEL_PRIMARY",
  "CMIP_GEMINI_MODEL_FALLBACK",
  "CMIP_GEMINI_MODEL_REPAIR",
  "CMIP_GEMINI_TIMEOUT_MS",
  "CMIP_GEMINI_MAX_ATTEMPTS",
  "CMIP_GEMINI_MAX_OUTPUT_TOKENS",
  "CMIP_GEMINI_THINKING_LEVEL",
  "CMIP_GEMINI_ENABLE_GOOGLE_SEARCH",
  "CMIP_PROVIDER_PRIMARY",
  "CMIP_PROVIDER_FALLBACK",
  "CMIP_ALLOW_LIVE_GEMINI_SMOKE",
] as const;

export const CMIP_GEMINI_DEFAULTS = {
  maxOutputTokens: 8000,
  timeoutMs: 240000,
  maxAttempts: 2,
  schemaRepairAttempts: 1,
  thinkingLevel: "auto",
} as const;

export const CMIP_GEMINI_PROVIDER_SCHEMA_STRIPPED_KEYS = ["$schema", "$id"] as const;
export const CMIP_GEMINI_UNSAFE_SCHEMA_KEYWORDS = [
  "$dynamicRef",
  "$dynamicAnchor",
  "patternProperties",
  "unevaluatedProperties",
  "unevaluatedItems",
  "dependentSchemas",
] as const;

export const CMIP_GEMINI_POST_VALIDATED_SCHEMA_KEYWORDS = ["oneOf", "if", "then", "else", "dependentRequired"] as const;
