export const CMIP_OPENAI_EXECUTION_VERSION = "CMIP-OPENAI-EXECUTION-1.0";
export const CMIP_OPENAI_ADAPTER_VERSION = "CMIP-OPENAI-ADAPTER-1.0";
export const CMIP_OPENAI_RESULT_SCHEMA_ID = "https://cmip.local/openai/execution-result-schema.v1.json";
export const CMIP_OPENAI_SCHEMA_COMPATIBILITY_VERSION = "CMIP-OPENAI-SCHEMA-COMPAT-1.0";
export const CMIP_OPENAI_RETRY_POLICY_VERSION = "CMIP-OPENAI-RETRY-1.0";
export const CMIP_OPENAI_TOOL_MAPPER_VERSION = "CMIP-OPENAI-TOOL-MAPPER-1.0";

export const CMIP_OPENAI_EXECUTION_STATUSES = ["success", "failed", "refused", "incomplete"] as const;

export const CMIP_OPENAI_ERROR_CODES = [
  "INVALID_EXECUTION_REQUEST",
  "OPENAI_CONFIG_MISSING",
  "OPENAI_LIVE_SMOKE_NOT_ALLOWED",
  "MODEL_PROFILE_NOT_CONFIGURED",
  "MODEL_CAPABILITY_UNSUPPORTED",
  "MODEL_PACKAGE_INVALID",
  "MODEL_PACKAGE_INTEGRITY_INVALID",
  "OUTPUT_SCHEMA_MISMATCH",
  "OUTPUT_SCHEMA_UNSUPPORTED",
  "OPENAI_REQUEST_MAPPING_FAILED",
  "OPENAI_REQUEST_FAILED",
  "OPENAI_RATE_LIMITED",
  "OPENAI_TIMEOUT",
  "OPENAI_TRANSPORT_ERROR",
  "OPENAI_PROVIDER_5XX",
  "OPENAI_AUTH_ERROR",
  "MODEL_RESPONSE_INCOMPLETE",
  "MODEL_RESPONSE_FAILED",
  "MODEL_REFUSAL",
  "MODEL_OUTPUT_MISSING",
  "MODEL_OUTPUT_JSON_INVALID",
  "MODEL_OUTPUT_SCHEMA_INVALID",
  "SCHEMA_REPAIR_FAILED",
  "EXECUTION_RESULT_INVALID",
  "SECRET_LEAK_DETECTED",
] as const;

export const CMIP_OPENAI_WARNING_CODES = [
  "OPENAI_TOOL_DISABLED",
  "OPENAI_WEB_SEARCH_DISABLED_BY_ENV",
  "OPENAI_WEB_SEARCH_UNSUPPORTED_BY_MODEL",
  "OPENAI_SCHEMA_COMPATIBILITY_TRANSFORMED",
  "OPENAI_SCHEMA_REPAIR_ATTEMPTED",
  "OPENAI_RETRY_ATTEMPTED",
  "OPENAI_FALLBACK_MODEL_USED",
  "OPENAI_USAGE_UNAVAILABLE",
  "OPENAI_TOOL_SOURCE_RECORDED",
] as const;

export const CMIP_OPENAI_RESPONSE_RETRYABLE_ERROR_CODES = [
  "OPENAI_RATE_LIMITED",
  "OPENAI_TIMEOUT",
  "OPENAI_TRANSPORT_ERROR",
  "OPENAI_PROVIDER_5XX",
] as const;

export const CMIP_OPENAI_ENV_KEYS = [
  "OPENAI_API_KEY",
  "OPENAI_PROJECT_ID",
  "OPENAI_ORGANIZATION_ID",
  "CMIP_OPENAI_MODEL_PRIMARY",
  "CMIP_OPENAI_MODEL_FALLBACK",
  "CMIP_OPENAI_MODEL_REPAIR",
  "CMIP_OPENAI_ENABLE_WEB_SEARCH",
  "CMIP_OPENAI_MAX_OUTPUT_TOKENS",
  "CMIP_OPENAI_TIMEOUT_MS",
  "CMIP_OPENAI_MAX_ATTEMPTS",
  "CMIP_OPENAI_REASONING_EFFORT",
  "CMIP_OPENAI_SERVICE_TIER",
  "CMIP_ALLOW_LIVE_OPENAI_SMOKE",
] as const;

export const CMIP_OPENAI_DEFAULTS = {
  maxOutputTokens: 8000,
  timeoutMs: 240000,
  maxAttempts: 2,
  schemaRepairAttempts: 1,
  reasoningEffort: "high",
  serviceTier: "auto",
} as const;

export const CMIP_OPENAI_PROVIDER_SCHEMA_STRIPPED_KEYS = ["$schema", "$id"] as const;
export const CMIP_OPENAI_UNSUPPORTED_STRICT_SCHEMA_KEYWORDS = [
  "patternProperties",
  "unevaluatedProperties",
  "dependentSchemas",
  "dependentRequired",
  "$dynamicRef",
  "$dynamicAnchor",
] as const;

export const CMIP_OPENAI_SECRET_PLACEHOLDER = "[REDACTED:CMIP_OPENAI_SECRET]";
