import type { IntelligenceAssetSymbol, IntelligenceSourceCategory, IntelligenceSourceConfig, SourceType, TimeHorizon } from "@/lib/types";
import type { SourceDefinition } from "@/types/ingestion";

const retryPolicy = {
  maxAttempts: 3,
  backoffMs: 800,
  backoffMultiplier: 2,
};

function optionalSourceEnabled(envKey: string) {
  return Boolean(process.env[envKey]);
}

export const productionSources: SourceDefinition[] = [
  {
    id: "cmip-public-market-signal-adapters",
    name: "C.M.I.P public macro and liquidity adapters",
    sourceType: "api",
    category: "market_data",
    tier: 1,
    enabled: true,
    pollingIntervalSeconds: 30 * 60,
    timeoutMs: 10_000,
    priorityScore: 100,
    parser: "market_signals",
    assetRelevance: ["BTC", "ETH", "SOL", "DXY", "Gold", "Nasdaq", "US10Y", "VIX", "Stablecoins"],
    signalKeys: [
      "btc_trend_24h",
      "eth_trend_24h",
      "sol_trend_24h",
      "btc_market_cap",
      "eth_market_cap",
      "sol_market_cap",
      "nasdaq_trend_24h",
      "dxy_trend_24h",
      "us10y_trend_24h",
      "gold_trend_24h",
      "vix_trend_24h",
      "usdt_supply_7d",
      "usdc_supply_7d",
      "stablecoin_market_cap_7d",
      "stablecoin_market_cap_30d",
      "total_stablecoin_market_cap_usd",
      "stablecoin_dominance",
      "funding_btc",
      "funding_eth",
      "funding_sol",
      "open_interest_btc_24h",
      "open_interest_eth_24h",
      "open_interest_sol_24h",
      "spot_volume_btc_24h",
      "spot_volume_eth_24h",
      "spot_volume_sol_24h",
      "futures_volume_btc_24h",
      "futures_volume_eth_24h",
      "futures_volume_sol_24h",
      "btc_etf_flow_24h",
      "eth_etf_flow_24h",
      "exchange_reserves_btc_7d",
      "exchange_inflows",
      "exchange_outflows",
      "news_sentiment_macro",
      "geopolitical_event_score",
    ],
    retryPolicy,
    rateLimitPerMinute: 12,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
    blocksCoreIntelligence: true,
  },
  {
    id: "binance-public-rest",
    name: "Binance public REST",
    sourceType: "api",
    endpoint: "https://api.binance.com",
    category: "market_data",
    tier: 1,
    enabled: true,
    pollingIntervalSeconds: 5 * 60,
    timeoutMs: 8_000,
    priorityScore: 96,
    parser: "exchange_market",
    assetRelevance: ["BTC", "ETH", "SOL"],
    retryPolicy,
    rateLimitPerMinute: 60,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
    blocksCoreIntelligence: true,
  },
  {
    id: "bybit-public-rest",
    name: "Bybit public REST",
    sourceType: "api",
    endpoint: "https://api.bybit.com",
    category: "market_data",
    tier: 2,
    enabled: true,
    pollingIntervalSeconds: 5 * 60,
    timeoutMs: 8_000,
    priorityScore: 82,
    parser: "exchange_market",
    assetRelevance: ["BTC", "ETH", "SOL"],
    retryPolicy,
    rateLimitPerMinute: 60,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
  },
  {
    id: "fed-press-rss",
    name: "Federal Reserve RSS",
    sourceType: "rss",
    endpoint: "https://www.federalreserve.gov/feeds/press_all.xml",
    category: "central_banks",
    tier: 1,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 98,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "DXY", "Gold", "Nasdaq", "US10Y"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "mark_unavailable",
    accessModel: "core_free",
    intelligenceClass: "core",
    blocksCoreIntelligence: true,
  },
  {
    id: "ecb-press-rss",
    name: "ECB RSS",
    sourceType: "rss",
    endpoint: "https://www.ecb.europa.eu/rss/press.html",
    category: "central_banks",
    tier: 2,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 88,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "DXY", "Gold", "Nasdaq", "US10Y"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
  },
  {
    id: "treasury-press-rss",
    name: "US Treasury public press releases",
    sourceType: "scraper",
    endpoint: "https://home.treasury.gov/news/press-releases/",
    category: "geopolitics",
    tier: 1,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 94,
    parser: "html_listing",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT", "DXY", "Gold", "US10Y"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "mark_unavailable",
    accessModel: "scraping_fallback",
    intelligenceClass: "core",
  },
  {
    id: "sec-press-rss",
    name: "SEC public press releases",
    sourceType: "filings",
    endpoint: "https://www.sec.gov/news/pressreleases.rss",
    category: "financial_media",
    tier: 2,
    enabled: true,
    pollingIntervalSeconds: 15 * 60,
    timeoutMs: 8_000,
    priorityScore: 86,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT"],
    retryPolicy,
    rateLimitPerMinute: 4,
    degradedMode: "mark_unavailable",
    accessModel: "free_delayed",
    intelligenceClass: "core",
  },
  {
    id: "coindesk-rss",
    name: "CoinDesk RSS",
    sourceType: "rss",
    endpoint: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    category: "crypto_media",
    tier: 2,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 82,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
  },
  {
    id: "theblock-rss",
    name: "The Block RSS",
    sourceType: "rss",
    endpoint: "https://www.theblock.co/rss.xml",
    category: "crypto_media",
    tier: 2,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 80,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
  },
  {
    id: "cointelegraph-rss",
    name: "Cointelegraph RSS",
    sourceType: "rss",
    endpoint: "https://cointelegraph.com/rss",
    category: "crypto_media",
    tier: 3,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 74,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
  },
  {
    id: "cnbc-markets-rss",
    name: "CNBC Markets RSS",
    sourceType: "rss",
    endpoint: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    category: "financial_media",
    tier: 2,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 82,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "DXY", "Gold", "Nasdaq", "US10Y"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "free_delayed",
    intelligenceClass: "core",
  },
  {
    id: "reuters-licensed-feed",
    name: "Reuters licensed feed",
    sourceType: "rss",
    category: "financial_media",
    tier: 2,
    enabled: false,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 84,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "DXY", "Gold", "Nasdaq", "US10Y"],
    retryPolicy,
    rateLimitPerMinute: 0,
    degradedMode: "allow_partial",
    accessModel: "premium_disabled",
    intelligenceClass: "premium",
    premiumModule: "licensed_financial_media",
    disabledReason: "Reuters realtime/licensed feed is disabled by default. C.M.I.P does not scrape paywalled Reuters content.",
  },
  {
    id: "decrypt-rss",
    name: "Decrypt RSS",
    sourceType: "rss",
    endpoint: "https://decrypt.co/feed",
    category: "crypto_media",
    tier: 3,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 70,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
  },
  {
    id: "cryptoslate-rss",
    name: "CryptoSlate RSS",
    sourceType: "rss",
    endpoint: "https://cryptoslate.com/feed/",
    category: "crypto_media",
    tier: 3,
    enabled: false,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 70,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
    disabledReason: "Latest verification returned HTTP 403 from the public feed. It stays registered but disabled to avoid noisy dead letters.",
  },
  {
    id: "blockworks-rss",
    name: "Blockworks RSS",
    sourceType: "rss",
    endpoint: "https://blockworks.co/feed",
    category: "crypto_media",
    tier: 3,
    enabled: true,
    pollingIntervalSeconds: 10 * 60,
    timeoutMs: 8_000,
    priorityScore: 72,
    parser: "rss",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "core_free",
    intelligenceClass: "core",
  },
  {
    id: "fred-api",
    name: "FRED API",
    sourceType: "api",
    endpoint: "https://api.stlouisfed.org/fred",
    category: "economic_data",
    tier: 2,
    enabled: optionalSourceEnabled("FRED_API_KEY"),
    pollingIntervalSeconds: 30 * 60,
    timeoutMs: 8_000,
    priorityScore: 95,
    parser: "market_signals",
    signalKeys: [
      "cpi_latest",
      "ppi_latest",
      "fed_funds_rate",
      "unemployment_rate",
      "us10y_trend_24h",
      "us2y_trend_24h",
      "yield_curve_10y2y",
      "dxy_trend_24h",
    ],
    assetRelevance: ["BTC", "ETH", "SOL", "DXY", "Gold", "Nasdaq", "US10Y"],
    requiredEnvKeys: ["FRED_API_KEY"],
    retryPolicy,
    rateLimitPerMinute: 10,
    degradedMode: "allow_partial",
    accessModel: "api_key_optional",
    intelligenceClass: "optional",
    disabledReason: "FRED_API_KEY optional; Yahoo/Stooq-style macro proxies keep core intelligence running when this is absent.",
  },
  {
    id: "trading-economics-api",
    name: "Trading Economics API",
    sourceType: "api",
    endpoint: "https://api.tradingeconomics.com",
    category: "economic_data",
    tier: 2,
    enabled: optionalSourceEnabled("TRADINGECONOMICS_API_KEY"),
    pollingIntervalSeconds: 30 * 60,
    timeoutMs: 8_000,
    priorityScore: 84,
    parser: "json",
    assetRelevance: ["BTC", "ETH", "SOL", "DXY", "Gold", "Nasdaq", "US10Y"],
    requiredEnvKeys: ["TRADINGECONOMICS_API_KEY"],
    retryPolicy,
    rateLimitPerMinute: 8,
    degradedMode: "allow_partial",
    accessModel: "api_key_optional",
    intelligenceClass: "optional",
    disabledReason: "TRADINGECONOMICS_API_KEY optional; not required for core free/proxy analysis.",
  },
  {
    id: "whale-alert-api",
    name: "Whale Alert API",
    sourceType: "api",
    endpoint: "https://api.whale-alert.io",
    category: "onchain",
    tier: 2,
    enabled: optionalSourceEnabled("WHALE_ALERT_API_KEY"),
    pollingIntervalSeconds: 15 * 60,
    timeoutMs: 8_000,
    priorityScore: 82,
    parser: "json",
    assetRelevance: ["BTC", "ETH", "SOL", "USDT"],
    requiredEnvKeys: ["WHALE_ALERT_API_KEY"],
    retryPolicy,
    rateLimitPerMinute: 8,
    degradedMode: "allow_partial",
    accessModel: "api_key_optional",
    intelligenceClass: "optional",
    premiumModule: "whale_tracking",
    disabledReason: "WHALE_ALERT_API_KEY optional; whale attribution is an enrichment layer.",
  },
  {
    id: "coinglass-api",
    name: "CoinGlass API",
    sourceType: "api",
    endpoint: "https://open-api.coinglass.com",
    category: "derivatives",
    tier: 2,
    enabled: optionalSourceEnabled("COINGLASS_API_KEY"),
    pollingIntervalSeconds: 15 * 60,
    timeoutMs: 8_000,
    priorityScore: 90,
    parser: "json",
    assetRelevance: ["BTC", "ETH", "SOL"],
    requiredEnvKeys: ["COINGLASS_API_KEY"],
    retryPolicy,
    rateLimitPerMinute: 8,
    degradedMode: "allow_partial",
    accessModel: "api_key_optional",
    intelligenceClass: "optional",
    premiumModule: "derivatives_enrichment",
    disabledReason: "COINGLASS_API_KEY optional; Binance public funding/OI proxies keep leverage analysis available.",
  },
  {
    id: "glassnode-api",
    name: "Glassnode API",
    sourceType: "api",
    endpoint: "https://api.glassnode.com",
    category: "onchain",
    tier: 3,
    enabled: optionalSourceEnabled("GLASSNODE_API_KEY"),
    pollingIntervalSeconds: 30 * 60,
    timeoutMs: 8_000,
    priorityScore: 78,
    parser: "json",
    assetRelevance: ["BTC", "ETH"],
    requiredEnvKeys: ["GLASSNODE_API_KEY"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "api_key_optional",
    intelligenceClass: "optional",
    premiumModule: "deep_onchain",
    disabledReason: "GLASSNODE_API_KEY optional; unavailable values are not fabricated.",
  },
  {
    id: "cryptoquant-api",
    name: "CryptoQuant API",
    sourceType: "api",
    endpoint: "https://api.cryptoquant.com",
    category: "onchain",
    tier: 3,
    enabled: optionalSourceEnabled("CRYPTOQUANT_API_KEY"),
    pollingIntervalSeconds: 30 * 60,
    timeoutMs: 8_000,
    priorityScore: 78,
    parser: "json",
    assetRelevance: ["BTC", "ETH", "USDT"],
    requiredEnvKeys: ["CRYPTOQUANT_API_KEY"],
    retryPolicy,
    rateLimitPerMinute: 6,
    degradedMode: "allow_partial",
    accessModel: "api_key_optional",
    intelligenceClass: "optional",
    premiumModule: "exchange_reserves",
    disabledReason: "CRYPTOQUANT_API_KEY optional; exchange reserve analysis remains unavailable until configured.",
  },
];

export function getEnabledSources() {
  return productionSources.filter((source) => source.enabled);
}

export function getAllSources() {
  return productionSources;
}

export function findSourceById(sourceId: string) {
  return productionSources.find((source) => source.id === sourceId) ?? null;
}

const categoryLabelsFa: Record<string, string> = {
  central_banks: "بانک‌های مرکزی / سیاست پولی",
  economic_data: "داده‌های اقتصادی / تقویم",
  financial_media: "رسانه‌های مالی",
  crypto_media: "رسانه‌های کریپتو",
  onchain: "آن‌چین",
  derivatives: "مشتقات / اهرم",
  stablecoins: "استیبل‌کوین / نقدینگی",
  etf: "ETF / جریان نهادی",
  sentiment: "سنتیمنت / شبکه‌های اجتماعی",
  geopolitics: "ژئوپلیتیک / امنیت",
  alternative_data: "داده جایگزین",
  exchange_health: "سلامت صرافی",
  volatility_regime: "نوسان / رژیم",
  market_data: "داده بازار / همبستگی",
  source_health: "سلامت منابع",
};

const intelligenceCategoryBySourceCategory: Record<string, IntelligenceSourceCategory> = {
  central_banks: "Central Banks / Macro Policy",
  economic_data: "Economic Data / Calendar",
  financial_media: "Newswires / Financial Media",
  crypto_media: "Newswires / Financial Media",
  onchain: "On-chain Analytics",
  derivatives: "Derivatives / Leverage",
  stablecoins: "Stablecoin / Liquidity Flows",
  etf: "ETF Flows / Institutional Flows",
  sentiment: "Sentiment / Social Intelligence",
  geopolitics: "Geopolitics / Security",
  alternative_data: "AI / Alternative Data",
  exchange_health: "Exchange Health / Risk",
  volatility_regime: "Fear / Volatility / Regime",
  market_data: "Market Data / Correlations",
  source_health: "Smart Alert Sources",
};

function toSourceType(source: SourceDefinition): SourceType {
  if (source.sourceType === "api" || source.sourceType === "websocket") return "API";
  if (source.sourceType === "rss") return "RSS";
  if (source.sourceType === "scraper" || source.sourceType === "filings") return "crawler";
  if (source.sourceType === "social") return "manual";
  return "manual";
}

function horizonRelevance(source: SourceDefinition): TimeHorizon[] {
  if (source.category === "central_banks" || source.category === "geopolitics") return ["short", "medium", "long"];
  if (source.category === "market_data") return ["short", "medium"];
  return ["short"];
}

export function getSourcesForAsset(asset: IntelligenceAssetSymbol, horizon?: TimeHorizon): IntelligenceSourceConfig[] {
  return productionSources
    .filter((source) => source.assetRelevance.includes(asset))
    .map((source) => {
      const horizons = horizonRelevance(source);
      return {
        id: source.id,
        name: source.name,
        category: intelligenceCategoryBySourceCategory[source.category] ?? "AI / Alternative Data",
        sourceType: toSourceType(source),
        assetRelevance: source.assetRelevance.filter((item): item is IntelligenceAssetSymbol =>
          ["BTC", "ETH", "SOL", "USDT", "DXY", "Gold", "Nasdaq", "US10Y"].includes(item),
        ),
        horizonRelevance: horizons,
        reliabilityScore: source.priorityScore,
        updateFrequency: `هر ${Math.max(1, Math.round(source.pollingIntervalSeconds / 60))} دقیقه`,
        currentStatus: "unavailable",
        notes: "این منبع در registry تولیدی ثبت شده است؛ وضعیت واقعی آن از source health و آخرین اجرای ingestion خوانده می‌شود.",
      } satisfies IntelligenceSourceConfig;
    })
    .filter((source) => !horizon || source.horizonRelevance.includes(horizon));
}

export function summarizeSources() {
  const grouped = new Map<string, { category: string; labelFa: string; count: number; rss: number; api: number; crawler: number }>();

  for (const source of productionSources) {
    const row = grouped.get(source.category) ?? {
      category: source.category,
      labelFa: categoryLabelsFa[source.category] ?? source.category,
      count: 0,
      rss: 0,
      api: 0,
      crawler: 0,
    };
    row.count += 1;
    if (source.sourceType === "rss") row.rss += 1;
    else if (source.sourceType === "api" || source.sourceType === "websocket") row.api += 1;
    else row.crawler += 1;
    grouped.set(source.category, row);
  }

  return Array.from(grouped.values()).sort((left, right) => right.count - left.count || left.labelFa.localeCompare(right.labelFa));
}
